package com.mycompany.datastructuresca1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * 14/03/24
 * PlayListGUI.java
 * @author Ryan Stokes
 */
public class MusicManagerApp extends javax.swing.JFrame {

    public MusicManagerApp() {
        initComponents();
    }
    
    //Data Memebers
    MusicManager ls = new MusicManager();
    DefaultListModel lmLikedSongs = new DefaultListModel();
    DefaultListModel lmRock = new DefaultListModel();
    DefaultListModel lmElectronic = new DefaultListModel();
    Timer timer;
    int currentIndex = 1;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenre = new javax.swing.ButtonGroup();
        txtSongName = new javax.swing.JTextField();
        rdoRock = new javax.swing.JRadioButton();
        rdoElectronic = new javax.swing.JRadioButton();
        lblSongName = new javax.swing.JLabel();
        btnAddSong = new javax.swing.JButton();
        btnAddGenre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLikedSongs = new javax.swing.JList<>();
        lblLikedSongs = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGenre = new javax.swing.JList<>();
        lblGenreList = new javax.swing.JLabel();
        txtArtist = new javax.swing.JTextField();
        lblArtist = new javax.swing.JLabel();
        btnGenreChange = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblGenrePlaylist = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblSongCount = new javax.swing.JLabel();
        txtSongCount = new javax.swing.JTextField();
        btnRepeat = new javax.swing.JButton();
        lblCurrent = new javax.swing.JLabel();
        lblCurrentSong = new javax.swing.JLabel();
        btnMoveUp = new javax.swing.JButton();
        btnMoveDown = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSongName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSongNameActionPerformed(evt);
            }
        });

        buttonGroupGenre.add(rdoRock);
        rdoRock.setText("Rock");

        buttonGroupGenre.add(rdoElectronic);
        rdoElectronic.setText("Electronic");

        lblSongName.setText("Song Name:");

        btnAddSong.setText("Add Song");
        btnAddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSongActionPerformed(evt);
            }
        });

        btnAddGenre.setText("Add Genre");
        btnAddGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGenreActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstLikedSongs);

        lblLikedSongs.setText("Liked Songs:");

        jScrollPane3.setViewportView(lstGenre);

        lblGenreList.setText("Rock");

        lblArtist.setText("Artist");

        btnGenreChange.setText("Next Genre");
        btnGenreChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreChangeActionPerformed(evt);
            }
        });

        lblSearch.setText("Search Playlist");

        lblGenrePlaylist.setText("Genre Playlists");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblSongCount.setText("Song Count:");

        txtSongCount.setEditable(false);
        txtSongCount.setText("0");

        btnRepeat.setText("Repeat Playlist");
        btnRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepeatActionPerformed(evt);
            }
        });

        lblCurrent.setText("Currently Playing:");

        lblCurrentSong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentSong.setText("None");

        btnMoveUp.setText("Move Down");
        btnMoveUp.setEnabled(false);
        btnMoveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveUpActionPerformed(evt);
            }
        });

        btnMoveDown.setText("Move Up");
        btnMoveDown.setEnabled(false);
        btnMoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveDownActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSongName)
                            .addComponent(lblLikedSongs)
                            .addComponent(lblArtist)
                            .addComponent(lblSearch)
                            .addComponent(lblGenrePlaylist))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(txtSongName)
                                .addComponent(txtArtist))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblSongCount))
                                    .addComponent(txtSearch))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSongCount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSearch)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnMoveDown)))))
                        .addGap(18, 18, 18)
                        .addComponent(btnMoveUp)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrent)
                        .addGap(173, 173, 173)
                        .addComponent(lblCurrentSong, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnRepeat)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddGenre)
                        .addComponent(rdoElectronic, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGenreChange)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(rdoRock)
                    .addComponent(btnAddSong)
                    .addComponent(btnStop))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblGenreList)
                .addGap(502, 502, 502))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(rdoRock)
                        .addGap(18, 18, 18)
                        .addComponent(rdoElectronic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnAddGenre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArtist))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSongName)
                            .addComponent(btnAddSong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLikedSongs))))
                .addGap(36, 36, 36)
                .addComponent(lblGenreList)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenreChange)
                    .addComponent(lblGenrePlaylist))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSongCount)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearch)
                            .addComponent(btnDelete)
                            .addComponent(btnMoveUp)
                            .addComponent(btnMoveDown)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRepeat)
                            .addComponent(lblCurrent)
                            .addComponent(lblCurrentSong)
                            .addComponent(btnStop))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSongCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGenreActionPerformed
        //Sorts Songs into selected playlist depending on radio button choice
        if(rdoRock.isSelected()){
            
            ls.addGenreA();
            lmRock.add(0, ls.sortGenreA());
            //Sets the list model depending on which playlist is visible to the user
            if(lblGenreList.getText() == "Rock"){
                lstGenre.setModel(lmRock);
                txtSongCount.setText(ls.countA());
            }
            //Removes song from liked songs playlist when it has been deleted from the liked songs stack
            lmLikedSongs.removeElementAt(0);
            
        }
        else if(rdoElectronic.isSelected()){
            
            ls.addGenreB();
            lmElectronic.add(0, ls.sortGenreB());
            //Sets the list model depending on which playlist is visible to the user
            if(lblGenreList.getText() == "Electronic"){
                lstGenre.setModel(lmElectronic);
                txtSongCount.setText(ls.countB());
            }
            //Removes song from liked songs playlist when it has been deleted from the liked songs stack
            lmLikedSongs.removeElementAt(0);
            
        }
        //Pop up alert if no button is selected
        else{
            
            JOptionPane.showMessageDialog(null, "Please Select a Genre");
        }
        
    }//GEN-LAST:event_btnAddGenreActionPerformed

    private void txtSongNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSongNameActionPerformed

    private void btnAddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSongActionPerformed
        ls.addLikedSong(txtSongName.getText(), txtArtist.getText());
        lmLikedSongs.add(0, ls.sortLikedSongs());
        lstLikedSongs.setModel(lmLikedSongs);
        txtSongName.setText(null);
        txtArtist.setText(null);
    }//GEN-LAST:event_btnAddSongActionPerformed

    private void btnGenreChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreChangeActionPerformed
        //Depending on which playlist is selected to be visible the list model is updated
        if(lblGenreList.getText() == "Rock"){
            
            lblGenreList.setText("Electronic");
            lstGenre.setModel(lmElectronic);
            txtSongCount.setText("0");
            txtSongCount.setText(ls.countB());
            
        }
        else{
         
            lblGenreList.setText("Rock");
            lstGenre.setModel(lmRock);
            txtSongCount.setText("0");
            txtSongCount.setText(ls.countA());
            
        }
    }//GEN-LAST:event_btnGenreChangeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(lblGenreList.getText() == "Rock"){
            
            if(ls.containsA(txtSearch.getText())){
            
                JOptionPane.showMessageDialog(null, "This song is in the Rock playlist");
                btnMoveUp.setEnabled(true);
                btnMoveDown.setEnabled(true);
                btnDelete.setEnabled(true);
        }
            else{
                
                JOptionPane.showMessageDialog(null, "This song is not in the Rock playlist");
                
            }
            
        }
        else{
            
            if(ls.containsB(txtSearch.getText())){
            
                JOptionPane.showMessageDialog(null, "This song is in the Electronic playlist");
                btnMoveUp.setEnabled(true);
                btnMoveDown.setEnabled(true);
                btnDelete.setEnabled(true);
            
        }
            else{
                
                JOptionPane.showMessageDialog(null, "This song is not in the Electronic playlist");
                
            }
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        if(ls.containsA(txtSearch.getText()) || ls.containsB(txtSearch.getText())){
            if(lblGenreList.getText() == "Rock"){

            ls.deleteA(txtSearch.getText());
            lmRock.clear();
            for(int i = 0; i < ls.sizeA(); i++){

                lmRock.add(0, ls.iterateA(i));

            }
            lstGenre.setModel(lmRock);
            txtSongCount.setText("0");
            txtSongCount.setText(ls.countA());

            }
            else{

            ls.deleteB(txtSearch.getText());
            lmElectronic.clear();
            for(int i = 0; i < ls.sizeB(); i++){

                lmElectronic.add(0, ls.iterateB(i));

            }
            lstGenre.setModel(lmElectronic);
            txtSongCount.setText("0");
            txtSongCount.setText(ls.countB());

            }
        }
        else{
            
            JOptionPane.showMessageDialog(null, "This song is not in the selected playlist");
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnMoveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveDownActionPerformed

        ls.moveUpA(txtSearch.getText());
        lmRock.clear();
        for(int i = 0; i < ls.sizeA(); i++){

            lmRock.add(0, ls.iterateA(i));
            System.out.println(i);
        }
        lstGenre.setModel(lmRock);
    }//GEN-LAST:event_btnMoveDownActionPerformed

    private void btnMoveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveUpActionPerformed

        ls.moveDownA(txtSearch.getText());
        lmRock.clear();
        for(int i = 0; i < ls.sizeA(); i++){

            lmRock.add(0, ls.iterateA(i));
            System.out.println(i);
        }
        lstGenre.setModel(lmRock);
    }//GEN-LAST:event_btnMoveUpActionPerformed

    private void btnRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepeatActionPerformed
        
        if(lblGenreList.getText() == "Rock"){
            lblCurrentSong.setText(ls.iterateA(0));

            timer = new Timer(10000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (currentIndex < ls.sizeA()) {
                        lblCurrentSong.setText(ls.iterateA(currentIndex++));
                    } else {
                        timer.stop(); // Stop the timer when all items have been displayed
                        lblCurrentSong.setText("Finished displaying all items.");
                    }
                }
            });
            timer.start();
        }
        else{
            
            lblCurrentSong.setText(ls.iterateB(0));

            timer = new Timer(10000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (currentIndex < ls.sizeB()) {
                        lblCurrentSong.setText(ls.iterateB(currentIndex++));
                    } else {
                        timer.stop(); // Stop the timer when all items have been displayed
                        lblCurrentSong.setText("Finished displaying all items.");
                    }
                }
            });
            timer.start();
            
        }
    }//GEN-LAST:event_btnRepeatActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicManagerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGenre;
    private javax.swing.JButton btnAddSong;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGenreChange;
    private javax.swing.JButton btnMoveDown;
    private javax.swing.JButton btnMoveUp;
    private javax.swing.JButton btnRepeat;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnStop;
    private javax.swing.ButtonGroup buttonGroupGenre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblCurrentSong;
    private javax.swing.JLabel lblGenreList;
    private javax.swing.JLabel lblGenrePlaylist;
    private javax.swing.JLabel lblLikedSongs;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSongCount;
    private javax.swing.JLabel lblSongName;
    private javax.swing.JList<String> lstGenre;
    private javax.swing.JList<String> lstLikedSongs;
    private javax.swing.JRadioButton rdoElectronic;
    private javax.swing.JRadioButton rdoRock;
    private javax.swing.JTextField txtArtist;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSongCount;
    private javax.swing.JTextField txtSongName;
    // End of variables declaration//GEN-END:variables
}
