package com.mycompany.datastructuresca1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * 13/03/24
 * PlayListGUI.java
 * @author Ryan Stokes
 */
public class PlaylistGUI extends javax.swing.JFrame {

    public PlaylistGUI() {
        initComponents();
    }
    
    //Data Memebers
    SongSort ls = new SongSort();
    DefaultListModel lmLikedSongs = new DefaultListModel();
    DefaultListModel lmRock = new DefaultListModel();
    DefaultListModel lmElectronic = new DefaultListModel();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenre = new javax.swing.ButtonGroup();
        txtSongName = new javax.swing.JTextField();
        rdoRock = new javax.swing.JRadioButton();
        rdoElectronic = new javax.swing.JRadioButton();
        lblSongName = new javax.swing.JLabel();
        btnAddSong = new javax.swing.JButton();
        btnAddGenre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLikedSongs = new javax.swing.JList<>();
        lblLikedSongs = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGenre = new javax.swing.JList<>();
        lblGenreList = new javax.swing.JLabel();
        txtArtist = new javax.swing.JTextField();
        lblArtist = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblGenrePlaylist = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblSongCount = new javax.swing.JLabel();
        txtSongCount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSongName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSongNameActionPerformed(evt);
            }
        });

        buttonGroupGenre.add(rdoRock);
        rdoRock.setText("Rock");

        buttonGroupGenre.add(rdoElectronic);
        rdoElectronic.setText("Electronic");

        lblSongName.setText("Song Name:");

        btnAddSong.setText("Add Song");
        btnAddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSongActionPerformed(evt);
            }
        });

        btnAddGenre.setText("Add Genre");
        btnAddGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGenreActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstLikedSongs);

        lblLikedSongs.setText("Liked Songs:");

        jScrollPane3.setViewportView(lstGenre);

        lblGenreList.setText("Rock");

        lblArtist.setText("Artist");

        jButton1.setText("Next Genre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSearch.setText("Search Playlist");

        lblGenrePlaylist.setText("Genre Playlists");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        lblSongCount.setText("Song Count:");

        txtSongCount.setEditable(false);
        txtSongCount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(lblGenreList)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSongName)
                            .addComponent(lblLikedSongs)
                            .addComponent(lblArtist)
                            .addComponent(lblSearch)
                            .addComponent(lblGenrePlaylist))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearch)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(txtSongName)
                            .addComponent(txtArtist))
                        .addGap(65, 65, 65)
                        .addComponent(btnSearch)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAddGenre)
                                .addComponent(rdoElectronic, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(btnDelete))
                            .addComponent(rdoRock)
                            .addComponent(btnAddSong)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(lblSongCount)
                        .addGap(41, 41, 41)
                        .addComponent(txtSongCount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(rdoRock)
                        .addGap(18, 18, 18)
                        .addComponent(rdoElectronic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnAddGenre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArtist))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSongName)
                            .addComponent(btnAddSong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLikedSongs))))
                .addGap(36, 36, 36)
                .addComponent(lblGenreList)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lblGenrePlaylist))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSongCount)
                    .addComponent(txtSongCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGenreActionPerformed
        //Sorts Songs into selected playlist depending on radio button choice
        if(rdoRock.isSelected()){
            
            ls.addGenreA();
            lmRock.add(0, ls.sortGenreA());
            //Sets the list model depending on which playlist is visible to the user
            if(lblGenreList.getText() == "Rock"){
                lstGenre.setModel(lmRock);
                txtSongCount.setText(ls.countA());
            }
            //Removes song from liked songs playlist when it has been deleted from the liked songs stack
            lmLikedSongs.removeElementAt(0);
            
        }
        else if(rdoElectronic.isSelected()){
            
            ls.addGenreB();
            lmElectronic.add(0, ls.sortGenreB());
            //Sets the list model depending on which playlist is visible to the user
            if(lblGenreList.getText() == "Electronic"){
                lstGenre.setModel(lmElectronic);
                txtSongCount.setText(ls.countB());
            }
            //Removes song from liked songs playlist when it has been deleted from the liked songs stack
            lmLikedSongs.removeElementAt(0);
            
        }
        //Pop up alert if no button is selected
        else{
            
            JOptionPane.showMessageDialog(null, "Please Select a Genre");
        }
        
    }//GEN-LAST:event_btnAddGenreActionPerformed

    private void txtSongNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSongNameActionPerformed

    private void btnAddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSongActionPerformed
        ls.addLikedSong(txtSongName.getText(), txtArtist.getText());
        lmLikedSongs.add(0, ls.sortLikedSongs());
        lstLikedSongs.setModel(lmLikedSongs);
    }//GEN-LAST:event_btnAddSongActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Depending on which playlist is selected to be visible the list model is updated
        if(lblGenreList.getText() == "Rock"){
            
            lblGenreList.setText("Electronic");
            lstGenre.setModel(lmElectronic);
            txtSongCount.setText("0");
            txtSongCount.setText(ls.countB());
            
        }
        else{
         
            lblGenreList.setText("Rock");
            lstGenre.setModel(lmRock);
            txtSongCount.setText("0");
            txtSongCount.setText(ls.countA());
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(lblGenreList.getText() == "Rock"){
            
            if(ls.containsA(txtSearch.getText())){
            
                JOptionPane.showMessageDialog(null, "This song is in the Rock playlist");
            
        }
            else{
                
                JOptionPane.showMessageDialog(null, "This song is not in the Rock playlist");
                
            }
            
        }
        else{
            
            if(ls.containsB(txtSearch.getText())){
            
                JOptionPane.showMessageDialog(null, "This song is in the Electronic playlist");
            
        }
            else{
                
                JOptionPane.showMessageDialog(null, "This song is not in the Electronic playlist");
                
            }
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGenre;
    private javax.swing.JButton btnAddSong;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroupGenre;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblGenreList;
    private javax.swing.JLabel lblGenrePlaylist;
    private javax.swing.JLabel lblLikedSongs;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSongCount;
    private javax.swing.JLabel lblSongName;
    private javax.swing.JList<String> lstGenre;
    private javax.swing.JList<String> lstLikedSongs;
    private javax.swing.JRadioButton rdoElectronic;
    private javax.swing.JRadioButton rdoRock;
    private javax.swing.JTextField txtArtist;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSongCount;
    private javax.swing.JTextField txtSongName;
    // End of variables declaration//GEN-END:variables
}
